name: opensuse-tumbleweed-rmt-server

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

env:
  BASE_IMAGE: "registry.opensuse.org/opensuse/rmt-server:latest"
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Show variables
        run: |
          echo "Base image: ${{ env.BASE_IMAGE }}"

      # Check out repository
      - uses: actions/checkout@v2
        
