name: opensuse-tumbleweed-kiwi-ng

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

env:
  BASE_IMAGE_NAME: "registry.opensuse.org/opensuse/tumbleweed"
  BASE_IMAGE_TAG: "latest"
  TARGET_IMAGE_NAME: "opensuse-tumbleweed-kiwi-ng"
  WORK_CONTAINER: "work-container"
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Show variables
        run: |
          echo "Base image name: ${{ env.BASE_IMAGE_NAME }}"
          echo "Base image tag: ${{ env.BASE_IMAGE_TAG }}"
          echo "Target image name: ${{ env.TARGET_IMAGE_NAME }}"
      
      # Check out repository
      - uses: actions/checkout@v2
      
      # Pull base image
      - name: Pull base image
        run: buildah pull ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
      
      # Show images
      - name: Show images
        run: buildah images
        
      # Create work container
      - name: Create work container
        run: buildah from --name "${{ env.WORK_CONTAINER }}" ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
        
      # Show containers
      - name: Show containers
        run: buildah containers

      # Remove config
      - name: Remove config
        run: |
        
          buildah config --cmd "[]" ${{ env.WORK_CONTAINER }}
          buildah config --entrypoint "[]" ${{ env.WORK_CONTAINER }}
          buildah config --env - ${{ env.WORK_CONTAINER }}
          buildah config --port - ${{ env.WORK_CONTAINER }}
          buildah config --volume - ${{ env.WORK_CONTAINER }}
          buildah config --label - ${{ env.WORK_CONTAINER }}
      
      # Refresh repositories
      - name: Refresh repositories
        run: buildah run ${{ env.WORK_CONTAINER }} zypper refresh
      
      # Install updates
      #   tumbleweed: "zypper dup" not "zypper up"
      - name: Install updates
        run: buildah run ${{ env.WORK_CONTAINER }} zypper dup --no-confirm --no-recommends
