name: opensuse-tumbleweed-kiwi-ng

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

env:
  BASE_IMAGE_NAME: "registry.opensuse.org/opensuse/tumbleweed"
  BASE_IMAGE_TAG: "latest"
  TARGET_IMAGE_NAME: "opensuse-tumbleweed-kiwi-ng-testing"
  WORK_CONTAINER: "work-container"
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Show variables
        run: |
          echo "Base image name: ${{ env.BASE_IMAGE_NAME }}"
          echo "Base image tag: ${{ env.BASE_IMAGE_TAG }}"
          echo "Target image name: ${{ env.TARGET_IMAGE_NAME }}"
      
      # Check out repository
      - uses: actions/checkout@v2
      
      # Pull base image
      - name: Pull base image
        run: buildah pull ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
      
      # Show images
      - name: Show images
        run: buildah images
        
      # Create work container
      - name: Create work container
        run: buildah from --name "${{ env.WORK_CONTAINER }}" ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
        
      # Show containers
      - name: Show containers
        run: buildah containers

      # Remove config
      - name: Remove config
        run: |
          buildah config --cmd "[]" ${{ env.WORK_CONTAINER }}
          buildah config --entrypoint "[]" ${{ env.WORK_CONTAINER }}
          buildah config --env - ${{ env.WORK_CONTAINER }}
          buildah config --port - ${{ env.WORK_CONTAINER }}
          buildah config --volume - ${{ env.WORK_CONTAINER }}
          buildah config --label - ${{ env.WORK_CONTAINER }}
      
      # Refresh repositories
      - name: Refresh repositories
        run: buildah run ${{ env.WORK_CONTAINER }} zypper refresh
      
      # Install updates
      #   tumbleweed: "zypper dup" not "zypper up"
      - name: Install updates
        run: buildah run ${{ env.WORK_CONTAINER }} zypper dup --no-confirm --no-recommends
        
      # Add KIWI NG repository
      - name: Add KIWI NG repository
        run: |
          buildah run ${{ env.WORK_CONTAINER }} zypper addrepo http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Tumbleweed appliance-builder
          buildah run ${{ env.WORK_CONTAINER }} zypper --gpg-auto-import-keys refresh
            
      # Install KIWI NG
      - name: Add KIWI NG repository
        run: |
          buildah run ${{ env.WORK_CONTAINER }} buildah run ${{ env.WORK_CONTAINER }} zypper install --no-confirm --no-recommends python3-kiwi






      # Create target image
      - name: Create target image
        run: buildah commit --format docker --squash ${{ env.WORK_CONTAINER }} ${{ env.TARGET_IMAGE_NAME }}:${{ github.sha }}
      
      # Show images
      - name: Show images
        run: buildah images
        
      # Create additional tags
      - name: Create additional tags
        run: |
          buildah tag ${{ env.TARGET_IMAGE_NAME }}:${{ github.sha }} ${{ env.TARGET_IMAGE_NAME }}:${{ github.run_number }}  
          buildah tag ${{ env.TARGET_IMAGE_NAME }}:${{ github.sha }} ${{ env.TARGET_IMAGE_NAME }}:latest
      
      # Show images
      - name: Show images
        run: buildah images
      
      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.TARGET_IMAGE_NAME }}
          tags: latest ${{ github.run_number }} ${{ github.sha }}
          registry: ghcr.io/${{ github.repository_owner }}/container-images
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
