name: opensuse-tumbleweed-rmt-server

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Workflow name
        run: echo "${{ github.workflow }}"

      # Check out repository
      - uses: actions/checkout@v2
        
