name: sles-15-3-kiwi-ng

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

env:
  BASE_IMAGE_NAME: "registry.suse.com/suse/sle15"
  BASE_IMAGE_TAG: "15.3"
  TARGET_IMAGE_NAME: "sles-15-3-kiwi-ng"
  WORK_CONTAINER: "work-container"
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Show variables
        run: |
          echo "Base image name: ${{ env.BASE_IMAGE_NAME }}"
          echo "Base image tag: ${{ env.BASE_IMAGE_TAG }}"
          echo "Target image name: ${{ env.TARGET_IMAGE_NAME }}"
      
      # Check out repository
      - uses: actions/checkout@v2
      
      # Pull base image
      - name: Pull base image
        run: buildah pull ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
      
      # Show images
      - name: Show images
        run: buildah images
      
      # Create work container
      - name: Create work container
        run: buildah from --name "${{ env.WORK_CONTAINER }}" ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
        
      # Show containers
      - name: Show containers
        run: buildah containers
      
      # Inspect base image
      - name: Inspect base image
        run: buildah inspect --type image ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}





      # Create target image
      - name: Create target image
        run: buildah commit --format docker --squash ${{ env.WORK_CONTAINER }} ${{ env.TARGET_IMAGE_NAME }}:${{ github.sha }}
      
      # Show images
      - name: Show images
        run: buildah images
        
      # Create additional tags
      - name: Create additional tags
        run: |
          buildah tag ${{ env.TARGET_IMAGE_NAME }}:${{ github.sha }} ${{ env.TARGET_IMAGE_NAME }}:${{ github.run_number }}  
          buildah tag ${{ env.TARGET_IMAGE_NAME }}:${{ github.sha }} ${{ env.TARGET_IMAGE_NAME }}:latest
      
      # Show images
      - name: Show images
        run: buildah images
      
      # Push to ghcr.io
      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.TARGET_IMAGE_NAME }}
          tags: latest ${{ github.run_number }} ${{ github.sha }}
          registry: ghcr.io/${{ github.repository_owner }}/container-images
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
