name: sles-15-3-kiwi-ng

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

env:
  BASE_IMAGE_NAME: "registry.suse.com/suse/sle15"
  BASE_IMAGE_TAG: "15.3"
  TARGET_IMAGE_NAME: "sles-15-3-kiwi-ng"
  WORK_CONTAINER: "work-container"
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Show variables
        run: |
          echo "Base image name: ${{ env.BASE_IMAGE_NAME }}"
          echo "Base image tag: ${{ env.BASE_IMAGE_TAG }}"
          echo "Target image name: ${{ env.TARGET_IMAGE_NAME }}"
      
      # Check out repository
      - uses: actions/checkout@v2
      
      # Pull base image
      - name: Pull base image
        run: buildah pull ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
      
      # Show images
      - name: Show images
        run: buildah images
        
      # Create SCCcredentials
      - name: Create SCCcredentials
        run: |
          # Create SCCcredentials.tmp-1 and Creaate SCCcredentials.tmp-2
          touch $GITHUB_WORKSPACE/SCCcredentials.tmp-1
          echo "username=" >> $GITHUB_WORKSPACE/SCCcredentials.tmp-1
          echo "password=" >> $GITHUB_WORKSPACE/SCCcredentials.tmp-1
          touch $GITHUB_WORKSPACE/SCCcredentials.tmp-2
          echo "username=" >> $GITHUB_WORKSPACE/SCCcredentials.tmp-2
          echo "password=" >> $GITHUB_WORKSPACE/SCCcredentials.tmp-2
          # Create work container
          buildah from --name "${{ env.WORK_CONTAINER }}" ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
          # Install packages (SUSEConnect)
          buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials.tmp-1,dst=/run/secrets/SCCcredentials ${{ env.WORK_CONTAINER }} zypper install --no-confirm --no-recommends SUSEConnect
          # Register
          buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials.tmp-2,dst=/tmp/SCCcredentials ${{ env.WORK_CONTAINER }} SUSEConnect --regcode ${{ secrets.SCC_REGCODE_SLES }} --email ${{ secrets.SCC_EMAIL }}
          # Copy SCCcredentials
          cat /etc/zypp/credentials.d/SCCcredentials > /tmp/SCCcredentials
          cat /tmp/SCCcredentials
          # Unregister
          #buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials.tmp-2,dst=/etc/zypp/credentials.d/SCCcredentials ${{ env.WORK_CONTAINER }} SUSEConnect --de-register
          # Cleanup
          #buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials.tmp-2,dst=/etc/zypp/credentials.d/SCCcredentials ${{ env.WORK_CONTAINER }} SUSEConnect --cleanup
          # Remove SCCcredentials.tmp-1 and SCCcredentials.tmp-2
          #rm $GITHUB_WORKSPACE/SCCcredentials.tmp-1
          #rm $GITHUB_WORKSPACE/SCCcredentials.tmp-2
          
