name: sles-15-3-kiwi-ng

on:

  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * *'  # every day at midnight

env:
  BASE_IMAGE_NAME: "registry.suse.com/suse/sle15"
  BASE_IMAGE_TAG: "15.3"
  TARGET_IMAGE_NAME: "sles-15-3-kiwi-ng"
  WORK_CONTAINER: "work-container"
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Show variables
        run: |
          echo "Base image name: ${{ env.BASE_IMAGE_NAME }}"
          echo "Base image tag: ${{ env.BASE_IMAGE_TAG }}"
          echo "Target image name: ${{ env.TARGET_IMAGE_NAME }}"
      
      # Check out repository
      - uses: actions/checkout@v2
      
      # Pull base image
      - name: Pull base image
        run: buildah pull ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
      
      # Show images
      - name: Show images
        run: buildah images
        
      # Create SCC credentials
      - name: Create SCC credentials
        run: |
          # Create work container
          buildah from --name "${{ env.WORK_CONTAINER }}" ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
          # Install packages (SUSEConnect)
          buildah run ${{ env.WORK_CONTAINER }} zypper install --no-confirm --no-recommends SUSEConnect
          # Register
          buildah run ${{ env.WORK_CONTAINER }} SUSEConnect --regcode ${{ secrets.SCC_REGCODE_SLES }} --email ${{ secrets.SCC_EMAIL }}
          # Copy SCCcredentials from work container to build host
          mkdir $GITHUB_WORKSPACE/scc-creds
          buildah run -v $GITHUB_WORKSPACE/scc-creds:/scc-creds ${{ env.WORK_CONTAINER }} cp "/etc/zypp/credentials.d/SCCcredentials" "/scc-creds"
          mv $GITHUB_WORKSPACE/scc-creds/SCCcredentials $GITHUB_WORKSPACE
          rm -rf $GITHUB_WORKSPACE/scc-creds
          # Unregister
          buildah run ${{ env.WORK_CONTAINER }} SUSEConnect --de-register
          # Cleanup
          buildah run ${{ env.WORK_CONTAINER }} SUSEConnect --cleanup
          # Remove work container
          buildah rm ${{ env.WORK_CONTAINER }}
      
      # Show SCC credentials
      - name: Show SCC credentials
        run: cat $GITHUB_WORKSPACE/SCCcredentials
        
      # Create work container
      - name: Create work container
        run: buildah from --name "${{ env.WORK_CONTAINER }}" ${{ env.BASE_IMAGE_NAME }}:${{ env.BASE_IMAGE_TAG }}
      
      # Add additional modules
      - name: Add additional modules
        run: buildah config --env "ADDITIONAL_MODULES=PackageHub" ${{ env.WORK_CONTAINER }}
      
      # Add KIWI NG repository
      - name: Add KIWI NG repository
        run: buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials,dst=/run/secrets/SCCcredentials ${{ env.WORK_CONTAINER }} zypper addrepo http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/SLE_15_SP3 appliance-builder
      
      # Refresh repositories
      - name: Refresh repositories
        run: buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials,dst=/run/secrets/SCCcredentials ${{ env.WORK_CONTAINER }} zypper --gpg-auto-import-keys refresh
      
      # Show repositories
      - name: Show repositories
        run: buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials,dst=/run/secrets/SCCcredentials ${{ env.WORK_CONTAINER }} zypper lr
        
        
      
      ## Install updates
      #- name: Install updates
      #  run: buildah run --mount=type=bind,src=$GITHUB_WORKSPACE/SCCcredentials,dst=/run/secrets/SCCcredentials ${{ env.WORK_CONTAINER }} zypper update --no-confirm --no-recommends
      
      
      
        
        
        
          
          
          
          
